#!/bin/sh

#Only FullNode
#/home/pepe_orozco/go-evanesco/eva --datadir /home/pepe_orozco/go-evanesco/data --syncmode 'full' --port 30303 --rpc --rpcaddr '0.0.0.0' --rpccorsdomain "*" --rpcport 8545 --rpcapi 'personal,eth,net,web3,txpool,miner,clique' --ws --ws.addr '0.0.0.0' --ws.port 7777 --ws.api 'personal,eth,net,web3,txpool,miner,clique' --zkpvkpath ./verifykey.txt --config /home/pepe_orozco/go-evanesco/avis.toml

#FullNode and Miner
/home/pepe_orozco/go-evanesco/eva --datadir /home/pepe_orozco/go-evanesco/data --syncmode 'full' --port 30303 --rpc --rpcaddr '0.0.0.0' --rpccorsdomain "*" --rpcport 8545 --rpcapi 'personal,eth,net,web3,txpool,miner,clique' --ws --ws.addr '0.0.0.0' --ws.port 7777 --ws.api 'personal,eth,net,web3,txpool,miner,clique' --zkpminer --zkppkpath /home/pepe_orozco/go-evanesco/QmNpJg4jDFE4LMNvZUzysZ2Ghvo4UJFcsjguYcx4dTfwKx --zkpvkpath /home/pepe_orozco/go-evanesco/verifykey.txt --zkppassword ***** --config /home/pepe_orozco/go-evanesco/avis.toml
