#!/bin/sh
homeminer=xxx

$homeminer/miner mine --pk $HOME/QmNpJg4jDFE4LMNvZUzysZ2Ghvo4UJFcsjguYcx4dTfwKx --key $homeminer/keyfile.json --passwordfile $homeminer/pp --coinbase 0xFa7d41Ad4C48E98654186610463927Cf7Ff66f00
